### ISSUE TITLE
Renumber Object & Renumber Field

### ISSUE THREAD

**Issue by gmouftier** [BartPermentier/al-toolbox#37]
Hello,
Can you when i use "Renumber Object" get idRanges in appjson from start ID ? Instead of having the small proposal window
Can you add possibility skip Renumber field Table when i use "Renumber All Fields" ?
Best Regards,
Thanks in Advance.

**Comment by BartPermentier** [comment]
Hey,

1. I don't understand your first question. When you do the action "ALTB: Renumber AL Objects" you do not get a small proposal window and the app just renumbers based on your app.json ranges.
2. Ok we will look into it.

These devs will take some time since we have a lot of work at the moment. I will let you know once they are live.

**Comment by ankurinfy23** [comment]
i tried using it but it did not worked

**Comment by dsaveyn** [comment]
@ankurinfy23 could you elaborate? What exactly is not working?
