### ISSUE TITLE
pragma warning disable acting weird

### ISSUE THREAD

**Issue by GreatScott000** [BartPermentier/al-toolbox#61]
Why is does this say say "Surround [object Object" now and not the specific Analyzer code now?

![image](https://user-images.githubusercontent.com/4333956/142237586-a1763da2-c29b-4786-b3ff-616cc3827d29.png)

![image](https://user-images.githubusercontent.com/4333956/142237488-62e51331-ad31-4b85-9161-1c52d7e2f268.png)

**Comment by BartPermentier** [comment]
Hey, the functionality should only be used on codecop warnings. Don't use it to hide warnings that will become errors in future releases.

**Comment by GreatScott000** [comment]
I understand that but this is a conversion of a NAV project with 200+ reports and they all have this.

**Comment by nabmilbai** [comment]
Hello, we have faced with the same issue. It is a bit hard to fix all warnings right now due to dead line pressure... And to change [object Object] each time is also a little bit time consuming. If you do not mind, we should have an option to accept this new change or to proceed with previous one that will keep warning number. Is it possible to be done? 

Thank you in advance.

**Comment by BartPermentier** [comment]
Sure we will take a look at it when we have time. But don't expect a change before the end of the year we also have a lot of projects going live in January. You could make a branch and fix it yourself if you want this fixed sooner. Sorry

**Comment by jwikman** [comment]
The reason for this new weird behavior is a change in AL Language extension v8.2
The diagnostic code is now a hyperlink to the documentation. See screenshot:
![image](https://user-images.githubusercontent.com/23032645/142509144-050bdefe-52cb-4d74-a2cc-fa506c7194b9.png)

I'll see if I can fix this and create a PR.

**Comment by jwikman** [comment]
@BartPermentier please review my PR #62 to see if you like the approach of the fix.

This feature is used a lot by a lot of users, so it would be nice if we get this working again. :)

**Comment by jwikman** [comment]
The easiest workaround to get this to work again, if not obvious by my comment above, is to install AL Language Extension v8.1 or earlier.

Otherwise you can download the zip file below, unzip and install the vsix in VSCode. Then you'll have an unofficial version that solves this until @BartPermentier has the time to look into the issue.
[al-toolbox-2.0.17-jwikman.zip](https://github.com/BartPermentier/al-toolbox/files/7568435/al-toolbox-2.0.17-jwikman.zip)

**Comment by nabmilbai** [comment]
@jwikman Many thanks for your help. I do appreciate it. :) @BartPermentier Thank you in advance for considering jwikman PR when you guys will have some time.

**Comment by BartPermentier** [comment]
Published this now. Thanks @jwikman !
