### ISSUE TITLE
Dev/Debug Version in Marketplace?

### ISSUE THREAD

**Issue by dannoe** [BartPermentier/al-toolbox#71]
I tried to use the renumbering command but it did only renumber pages and pageextensions.
So I started to debug the github master branch and got some weird errors. I diffed marketplace version with the github version and spotted that the version in the marketplace is a debugging version with some stuff commented out and some console.log debug clutter.

Left Marketplace, Right Github master-branch

![grafik](https://user-images.githubusercontent.com/7450586/154092492-707c1d94-59bd-4ad5-8f2f-8b5aded90b85.png)

**Comment by dsaveyn** [comment]
We indeed build a vsix with some debug code in it, since the renumbering was not working as expected. Version 2.0.20 will be uploaded to the marketplace today with the debug code removed.

Place be aware that the renumbering is still not working as it should. In case of problems, a temporary workaround is to do the renumber in batches (folder per folder). We will further look into this issue in the future.
